### ISSUE TITLE
[Bug]: Build fail with Error: Cannot read properties of undefined (reading 'children')

### ISSUE THREAD

**Issue by xmlking** [sveltinio/sveltin#154] opened 2023-09-28 00:36 UTC
following [quick-start](https://docs.sveltin.io/quick-start/) guide , after adding `about`  page , 
when loading http://localhost:5173/about/ first time, getting this error. later it works fine 

<img width="919" alt="image" src="https://github.com/sveltinio/sveltin/assets/627951/a45e9fbf-5162-40fd-bbb5-c300b4a2bddd">

**Comment by indaco** [comment] 2023-09-28 10:40
@xmlking thanks for reporting it. Will work to fix it

**Comment by xmlking** [comment] 2023-10-01 02:07
same error also impacting build command 

<img width="1863" alt="image" src="https://github.com/sveltinio/sveltin/assets/627951/878346c0-b29c-4328-9f5e-6f77cd64b142">

**Comment by xmlking** [comment] 2023-10-01 06:23
looks like known issue SvelteKit + MDsveX
https://github.com/pngwn/MDsveX/issues/377

**Comment by indaco** [comment] 2023-10-01 07:04
That issue is 2 years old and, frankly speaking, never happened to my projects so far. Will check meanwhile can you share a basic repo or others reproducing it?


Can you also share info about your  environment? Node version, OS etc?


Thanks

**Comment by xmlking** [comment] 2023-10-01 08:02
https://github.com/xmlking/spectacular/tree/main/apps/docs
Node 20
MacOS sonoma

**Comment by indaco** [comment] 2023-10-01 08:43
Hi @xmlking 
The error is due to the usage of v2.0.1 for `remark-reading-time`, You must use **v1.0.1**

v2.0.1 introduces a **breaking**. You can read more [here](https://github.com/mattjennings/remark-reading-time/releases/tag/2.0.1). 

Quick summary:

"_If you were using this with mdsvex, this will break compatibility with it. However, https://github.com/pngwn/MDsveX/discussions/259 for unified plugins (remark / rehype), so it soon won't matter anyway. You can stay on v1 of remark-reading-time for the time being._"

So to fix it, downgrade `remark-reading-time` to **v1.0.1**

Let me know

**Comment by xmlking** [comment] 2023-10-01 16:53
Thanks a lot for research and finding the issue

**Comment by indaco** [comment] 2023-10-01 17:21
You are welcome!

I'm going to close this issue. 

Feel free to re-open it in case you need

**Closed** 2023-10-01 17:22 UTC

**Comment by xmlking** [comment] 2023-10-01 17:32
build sees progressed  after locking   remark-reading-time to v1.0.1
but prerender step keep failing.  `Error: 404 /posts/undefined/ (linked from /posts/undefined)`
wonder if you spot any misconfiguration I am doing 

<img width="1754" alt="image" src="https://github.com/sveltinio/sveltin/assets/627951/acb51079-9714-4a79-834e-a989487a0057">

**Comment by indaco** [comment] 2023-10-01 18:10
Did you add any content to the "posts" resource?

You have /posts/undefined

I would prefer to keep this closed as the issue has been identified. 

Feel free to open a new one to follow your new issue. 

My suggestion is to create a project from scratch and check if you have this issue there too. 

Not easy to me go through your existing monorepo. You have several own configurations in place (reference to internal packages to your monorepo etc)

**Comment by xmlking** [comment] 2023-10-01 18:18
I have content [https://github.com/xmlking/spectacular/tree/main/apps/docs/content/posts]
I have to lock `@sveltinio/widgets` to `0.6.1` to make successful build. 

in your `docs.sveltin.io` repo, you can reproduce by upgrading `@sveltinio/widgets` to latest.

**Comment by indaco** [comment] 2023-10-01 18:25
Can you open a new issue to track it, please? 

Thanks
